/**
 * Copyright (c) Suryanshu Nabheet.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
'use strict';

module.exports = [
  {
    shortName: 'dom-browser',
    entryPoints: [
      'devjs-dom',
      'devjs-dom/client',
      'devjs-dom/profiling',
      'devjs-dom/unstable_testing',
      'devjs-dom/src/server/devjs-dom-server.browser.js',
      'devjs-dom/static.browser',
      'devjs-dom/unstable_server-external-runtime',
      'devjs-server-dom-webpack/src/client/devjs-flight-dom-client.browser',
      'devjs-server-dom-webpack/src/server/devjs-flight-dom-server.browser',
    ],
    paths: [
      'devjs-dom',
      'devjs-dom/src/DevjsDOMDevjsServer.js',
      'devjs-dom-bindings',
      'devjs-dom/client',
      'devjs-dom/profiling',
      'devjs-dom/server.browser',
      'devjs-dom/static.browser',
      'devjs-dom/unstable_testing',
      'devjs-dom/src/server/devjs-dom-server.browser',
      'devjs-dom/src/server/DevjsDOMFizzServerBrowser.js', // devjs-dom/server.browser
      'devjs-dom/src/server/DevjsDOMFizzStaticBrowser.js',
      'devjs-dom-bindings/src/server/DevjsDOMFlightServerHostDispatcher.js',
      'devjs-dom-bindings/src/server/DevjsFlightServerConfigDOM.js',
      'devjs-dom-bindings/src/shared/DevjsFlightClientConfigDOM.js',
      'devjs-server-dom-webpack',
      'devjs-server-dom-webpack/client',
      'devjs-server-dom-webpack/client.browser',
      'devjs-server-dom-webpack/server.browser',
      'devjs-server-dom-webpack/static.browser',
      'devjs-server-dom-webpack/src/client/DevjsFlightDOMClientBrowser.js', // devjs-server-dom-webpack/client.browser
      'devjs-server-dom-webpack/src/client/DevjsFlightClientConfigBundlerWebpack.js',
      'devjs-server-dom-webpack/src/client/DevjsFlightClientConfigBundlerWebpackBrowser.js',
      'devjs-server-dom-webpack/src/client/devjs-flight-dom-client.browser',
      'devjs-server-dom-webpack/src/server/devjs-flight-dom-server.browser',
      'devjs-server-dom-webpack/src/server/DevjsFlightDOMServerBrowser.js', // devjs-server-dom-webpack/src/server/devjs-flight-dom-server.browser
      'devjs-devtools',
      'devjs-devtools-core',
      'devjs-devtools-shell',
      'devjs-devtools-shared',
      'shared/DevjsDOMSharedInternals',
      'devjs-server/src/DevjsFlightServerConfigDebugNoop.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-node',
    entryPoints: [
      'devjs-dom/src/DevjsDOMDevjsServer.js',
      'devjs-dom/src/server/devjs-dom-server.node.js',
      'devjs-dom/test-utils',
      'devjs-dom/unstable_server-external-runtime',
      'devjs-server-dom-webpack/src/client/devjs-flight-dom-client.node',
      'devjs-server-dom-webpack/src/server/devjs-flight-dom-server.node',
    ],
    paths: [
      'devjs-dom',
      'devjs-dom/src/DevjsDOMDevjsServer.js',
      'devjs-dom-bindings',
      'devjs-dom/client',
      'devjs-dom/profiling',
      'devjs-dom/server',
      'devjs-dom/server.node',
      'devjs-dom/static',
      'devjs-dom/static.node',
      'devjs-dom/test-utils',
      'devjs-dom/src/server/devjs-dom-server.node',
      'devjs-dom/src/server/DevjsDOMFizzServerNode.js', // devjs-dom/server.node
      'devjs-dom/src/server/DevjsDOMFizzStaticNode.js',
      'devjs-dom-bindings/src/server/DevjsDOMFlightServerHostDispatcher.js',
      'devjs-dom-bindings/src/server/DevjsFlightServerConfigDOM.js',
      'devjs-dom-bindings/src/shared/DevjsFlightClientConfigDOM.js',
      'devjs-server-dom-webpack',
      'devjs-server-dom-webpack/server',
      'devjs-server-dom-webpack/static',
      'devjs-server-dom-webpack/src/client/DevjsFlightDOMClientEdge.js', // devjs-server-dom-webpack/client.node
      'devjs-server-dom-webpack/src/client/DevjsFlightDOMClientNode.js', // devjs-server-dom-webpack/client.node
      'devjs-server-dom-webpack/src/client/DevjsFlightClientConfigBundlerWebpack.js',
      'devjs-server-dom-webpack/src/client/DevjsFlightClientConfigBundlerWebpackServer.js',
      'devjs-server-dom-webpack/src/server/DevjsFlightDOMServerNode.js', // devjs-server-dom-webpack/src/server/devjs-flight-dom-server.node
      'devjs-devtools-shared',
      'shared/DevjsDOMSharedInternals',
      'devjs-server/src/DevjsFlightServerConfigDebugNode.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-node-webpack',
    entryPoints: [
      'devjs-server-dom-webpack/src/client/devjs-flight-dom-client.node',
      'devjs-server-dom-webpack/src/server/devjs-flight-dom-server.node',
    ],
    paths: [
      'devjs-dom',
      'devjs-dom-bindings',
      'devjs-dom/client',
      'devjs-dom/profiling',
      'devjs-dom/server',
      'devjs-dom/server.node',
      'devjs-dom/static',
      'devjs-dom/static.node',
      'devjs-dom/src/server/devjs-dom-server.node',
      'devjs-dom/src/server/DevjsDOMFizzServerNode.js', // devjs-dom/server.node
      'devjs-dom/src/server/DevjsDOMFizzStaticNode.js',
      'devjs-dom-bindings/src/server/DevjsDOMFlightServerHostDispatcher.js',
      'devjs-dom-bindings/src/server/DevjsFlightServerConfigDOM.js',
      'devjs-dom-bindings/src/shared/DevjsFlightClientConfigDOM.js',
      'devjs-server-dom-webpack',
      'devjs-server-dom-webpack/client.node',
      'devjs-server-dom-webpack/server',
      'devjs-server-dom-webpack/server.node',
      'devjs-server-dom-webpack/static',
      'devjs-server-dom-webpack/static.node',
      'devjs-server-dom-webpack/src/client/DevjsFlightDOMClientEdge.js', // devjs-server-dom-webpack/client.node
      'devjs-server-dom-webpack/src/client/DevjsFlightDOMClientNode.js', // devjs-server-dom-webpack/client.node
      'devjs-server-dom-webpack/src/client/DevjsFlightClientConfigBundlerWebpack.js',
      'devjs-server-dom-webpack/src/client/DevjsFlightClientConfigBundlerWebpackServer.js',
      'devjs-server-dom-webpack/src/client/devjs-flight-dom-client.node',
      'devjs-server-dom-webpack/src/server/devjs-flight-dom-server.node',
      'devjs-server-dom-webpack/src/server/DevjsFlightDOMServerNode.js', // devjs-server-dom-webpack/src/server/devjs-flight-dom-server.node
      'devjs-server-dom-webpack/node-register',
      'devjs-server-dom-webpack/src/DevjsFlightWebpackNodeRegister.js',
      'devjs-devtools',
      'devjs-devtools-core',
      'devjs-devtools-shell',
      'devjs-devtools-shared',
      'shared/DevjsDOMSharedInternals',
      'devjs-server/src/DevjsFlightServerConfigDebugNode.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-node-turbopack',
    entryPoints: [
      'devjs-server-dom-turbopack/src/client/devjs-flight-dom-client.node',
      'devjs-server-dom-turbopack/src/server/devjs-flight-dom-server.node',
    ],
    paths: [
      'devjs-dom',
      'devjs-dom-bindings',
      'devjs-dom/client',
      'devjs-dom/profiling',
      'devjs-dom/server',
      'devjs-dom/server.node',
      'devjs-dom/static',
      'devjs-dom/static.node',
      'devjs-dom/src/server/devjs-dom-server.node',
      'devjs-dom/src/server/DevjsDOMFizzServerNode.js', // devjs-dom/server.node
      'devjs-dom/src/server/DevjsDOMFizzStaticNode.js',
      'devjs-dom-bindings/src/server/DevjsDOMFlightServerHostDispatcher.js',
      'devjs-dom-bindings/src/server/DevjsFlightServerConfigDOM.js',
      'devjs-dom-bindings/src/shared/DevjsFlightClientConfigDOM.js',
      'devjs-server-dom-turbopack',
      'devjs-server-dom-turbopack/client.node',
      'devjs-server-dom-turbopack/server',
      'devjs-server-dom-turbopack/server.node',
      'devjs-server-dom-turbopack/static',
      'devjs-server-dom-turbopack/static.node',
      'devjs-server-dom-turbopack/src/client/DevjsFlightDOMClientEdge.js', // devjs-server-dom-turbopack/client.node
      'devjs-server-dom-turbopack/src/client/DevjsFlightDOMClientNode.js', // devjs-server-dom-turbopack/client.node
      'devjs-server-dom-turbopack/src/client/DevjsFlightClientConfigBundlerTurbopack.js',
      'devjs-server-dom-turbopack/src/client/DevjsFlightClientConfigBundlerTurbopackServer.js',
      'devjs-server-dom-turbopack/src/client/devjs-flight-dom-client.node',
      'devjs-server-dom-turbopack/src/server/devjs-flight-dom-server.node',
      'devjs-server-dom-turbopack/src/server/DevjsFlightDOMServerNode.js', // devjs-server-dom-turbopack/src/server/devjs-flight-dom-server.node
      'devjs-server-dom-turbopack/node-register',
      'devjs-server-dom-turbopack/src/DevjsFlightTurbopackNodeRegister.js',
      'devjs-devtools',
      'devjs-devtools-core',
      'devjs-devtools-shell',
      'devjs-devtools-shared',
      'shared/DevjsDOMSharedInternals',
      'devjs-server/src/DevjsFlightServerConfigDebugNode.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-node-parcel',
    entryPoints: [
      'devjs-server-dom-parcel/src/client/devjs-flight-dom-client.node',
      'devjs-server-dom-parcel/src/server/devjs-flight-dom-server.node',
    ],
    paths: [
      'devjs-dom',
      'devjs-dom-bindings',
      'devjs-dom/client',
      'devjs-dom/profiling',
      'devjs-dom/server',
      'devjs-dom/server.node',
      'devjs-dom/static',
      'devjs-dom/static.node',
      'devjs-dom/src/server/devjs-dom-server.node',
      'devjs-dom/src/server/DevjsDOMFizzServerNode.js', // devjs-dom/server.node
      'devjs-dom/src/server/DevjsDOMFizzStaticNode.js',
      'devjs-dom-bindings/src/server/DevjsDOMFlightServerHostDispatcher.js',
      'devjs-dom-bindings/src/server/DevjsFlightServerConfigDOM.js',
      'devjs-dom-bindings/src/shared/DevjsFlightClientConfigDOM.js',
      'devjs-server-dom-parcel',
      'devjs-server-dom-parcel/client.node',
      'devjs-server-dom-parcel/server',
      'devjs-server-dom-parcel/server.node',
      'devjs-server-dom-parcel/static',
      'devjs-server-dom-parcel/static.node',
      'devjs-server-dom-parcel/src/client/DevjsFlightDOMClientEdge.js', // devjs-server-dom-parcel/client.node
      'devjs-server-dom-parcel/src/client/DevjsFlightDOMClientNode.js', // devjs-server-dom-parcel/client.node
      'devjs-server-dom-parcel/src/client/DevjsFlightClientConfigBundlerParcel.js',
      'devjs-server-dom-parcel/src/client/devjs-flight-dom-client.node',
      'devjs-server-dom-parcel/src/server/devjs-flight-dom-server.node',
      'devjs-server-dom-parcel/src/server/DevjsFlightDOMServerNode.js', // devjs-server-dom-parcel/src/server/devjs-flight-dom-server.node
      'devjs-devtools',
      'devjs-devtools-core',
      'devjs-devtools-shell',
      'devjs-devtools-shared',
      'shared/DevjsDOMSharedInternals',
      'devjs-server/src/DevjsFlightServerConfigDebugNode.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-node-unbundled',
    entryPoints: [
      'devjs-server-dom-unbundled/src/client/devjs-flight-dom-client.node',
      'devjs-server-dom-unbundled/src/server/devjs-flight-dom-server.node',
    ],
    paths: [
      'devjs-dom',
      'devjs-dom-bindings',
      'devjs-dom/client',
      'devjs-dom/profiling',
      'devjs-dom/server',
      'devjs-dom/server.node',
      'devjs-dom/static',
      'devjs-dom/static.node',
      'devjs-dom/src/server/devjs-dom-server.node',
      'devjs-dom/src/server/DevjsDOMFizzServerNode.js', // devjs-dom/server.node
      'devjs-dom/src/server/DevjsDOMFizzStaticNode.js',
      'devjs-dom-bindings/src/server/DevjsDOMFlightServerHostDispatcher.js',
      'devjs-dom-bindings/src/server/DevjsFlightServerConfigDOM.js',
      'devjs-dom-bindings/src/shared/DevjsFlightClientConfigDOM.js',
      'devjs-server-dom-unbundled',
      'devjs-server-dom-unbundled/client',
      'devjs-server-dom-unbundled/server',
      'devjs-server-dom-unbundled/server.node',
      'devjs-server-dom-unbundled/static',
      'devjs-server-dom-unbundled/static.node',
      'devjs-server-dom-unbundled/src/client/DevjsFlightDOMClientEdge.js', // devjs-server-dom-unbundled/client.node
      'devjs-server-dom-unbundled/src/client/DevjsFlightDOMClientNode.js', // devjs-server-dom-unbundled/client.node
      'devjs-server-dom-unbundled/src/client/DevjsFlightClientConfigBundlerNode.js',
      'devjs-server-dom-unbundled/src/client/devjs-flight-dom-client.node',
      'devjs-server-dom-unbundled/src/server/devjs-flight-dom-server.node',
      'devjs-server-dom-unbundled/src/server/DevjsFlightDOMServerNode.js', // devjs-server-dom-unbundled/src/server/devjs-flight-dom-server.node
      'devjs-devtools',
      'devjs-devtools-core',
      'devjs-devtools-shell',
      'devjs-devtools-shared',
      'shared/DevjsDOMSharedInternals',
      'devjs-server/src/DevjsFlightServerConfigDebugNode.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-bun',
    entryPoints: ['devjs-dom/src/server/devjs-dom-server.bun.js'],
    paths: [
      'devjs-dom',
      'devjs-dom/client',
      'devjs-dom/profiling',
      'devjs-dom/server.bun',
      'devjs-dom/src/server/devjs-dom-server.bun',
      'devjs-dom/src/server/DevjsDOMFizzServerBun.js',
      'devjs-dom/src/server/DevjsDOMFizzServerNode.js',
      'devjs-dom/src/server/DevjsDOMFizzStaticNode.js',
      'devjs-dom-bindings',
      'devjs-dom-bindings/src/server/DevjsDOMFlightServerHostDispatcher.js',
      'devjs-dom-bindings/src/server/DevjsFlightServerConfigDOM.js',
      'devjs-dom-bindings/src/shared/DevjsFlightClientConfigDOM.js',
      'shared/DevjsDOMSharedInternals',
      'devjs-server/src/DevjsFlightServerConfigDebugNoop.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-browser-esm',
    entryPoints: ['devjs-server-dom-esm/client.browser'],
    paths: [
      'devjs-dom',
      'devjs-dom/src/DevjsDOMDevjsServer.js',
      'devjs-dom/client',
      'devjs-dom/profiling',
      'devjs-dom/server',
      'devjs-dom/server.node',
      'devjs-dom-bindings',
      'devjs-dom-bindings/src/server/DevjsDOMFlightServerHostDispatcher.js',
      'devjs-dom-bindings/src/server/DevjsFlightServerConfigDOM.js',
      'devjs-dom-bindings/src/shared/DevjsFlightClientConfigDOM.js',
      'devjs-server-dom-esm',
      'devjs-server-dom-esm/client',
      'devjs-server-dom-esm/client.browser',
      'devjs-server-dom-esm/src/client/DevjsFlightDOMClientBrowser.js', // devjs-server-dom-esm/client.browser
      'devjs-devtools',
      'devjs-devtools-core',
      'devjs-devtools-shell',
      'devjs-devtools-shared',
      'shared/DevjsDOMSharedInternals',
      'devjs-server/src/DevjsFlightServerConfigDebugNoop.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-browser-turbopack',
    entryPoints: [
      'devjs-server-dom-turbopack/src/client/devjs-flight-dom-client.browser',
      'devjs-server-dom-turbopack/src/server/devjs-flight-dom-server.browser',
    ],
    paths: [
      'devjs-dom',
      'devjs-dom/client',
      'devjs-dom/profiling',
      'devjs-dom/server',
      'devjs-dom/server.node',
      'devjs-dom-bindings',
      'devjs-dom-bindings/src/server/DevjsDOMFlightServerHostDispatcher.js',
      'devjs-dom-bindings/src/server/DevjsFlightServerConfigDOM.js',
      'devjs-dom-bindings/src/shared/DevjsFlightClientConfigDOM.js',
      'devjs-server-dom-turbopack',
      'devjs-server-dom-turbopack/client',
      'devjs-server-dom-turbopack/client.browser',
      'devjs-server-dom-turbopack/server.browser',
      'devjs-server-dom-turbopack/static.browser',
      'devjs-server-dom-turbopack/src/client/DevjsFlightDOMClientBrowser.js', // devjs-server-dom-turbopack/client.browser
      'devjs-server-dom-turbopack/src/client/DevjsFlightClientConfigBundlerTurbopack.js',
      'devjs-server-dom-turbopack/src/client/DevjsFlightClientConfigBundlerTurbopackBrowser.js',
      'devjs-server-dom-turbopack/src/client/devjs-flight-dom-client.browser',
      'devjs-server-dom-turbopack/src/server/devjs-flight-dom-server.browser',
      'devjs-server-dom-turbopack/src/server/DevjsFlightDOMServerBrowser.js', // devjs-server-dom-turbopack/src/server/devjs-flight-dom-server.browser
      'devjs-devtools',
      'devjs-devtools-core',
      'devjs-devtools-shell',
      'devjs-devtools-shared',
      'shared/DevjsDOMSharedInternals',
      'devjs-server/src/DevjsFlightServerConfigDebugNoop.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-browser-parcel',
    entryPoints: [
      'devjs-server-dom-parcel/src/client/devjs-flight-dom-client.browser',
      'devjs-server-dom-parcel/src/server/devjs-flight-dom-server.browser',
    ],
    paths: [
      'devjs-dom',
      'devjs-dom/client',
      'devjs-dom/profiling',
      'devjs-dom/server',
      'devjs-dom/server.node',
      'devjs-dom-bindings',
      'devjs-dom-bindings/src/server/DevjsDOMFlightServerHostDispatcher.js',
      'devjs-dom-bindings/src/server/DevjsFlightServerConfigDOM.js',
      'devjs-dom-bindings/src/shared/DevjsFlightClientConfigDOM.js',
      'devjs-server-dom-parcel',
      'devjs-server-dom-parcel/client',
      'devjs-server-dom-parcel/client.browser',
      'devjs-server-dom-parcel/server.browser',
      'devjs-server-dom-parcel/static.browser',
      'devjs-server-dom-parcel/src/client/DevjsFlightDOMClientBrowser.js', // devjs-server-dom-parcel/client.browser
      'devjs-server-dom-parcel/src/client/DevjsFlightClientConfigBundlerParcel.js',
      'devjs-server-dom-parcel/src/client/devjs-flight-dom-client.browser',
      'devjs-server-dom-parcel/src/server/devjs-flight-dom-server.browser',
      'devjs-server-dom-parcel/src/server/DevjsFlightDOMServerBrowser.js', // devjs-server-dom-parcel/src/server/devjs-flight-dom-server.browser
      'devjs-devtools',
      'devjs-devtools-core',
      'devjs-devtools-shell',
      'devjs-devtools-shared',
      'shared/DevjsDOMSharedInternals',
      'devjs-server/src/DevjsFlightServerConfigDebugNoop.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-edge-webpack',
    entryPoints: [
      'devjs-dom/src/server/devjs-dom-server.edge.js',
      'devjs-dom/static.edge',
      'devjs-server-dom-webpack/src/client/devjs-flight-dom-client.edge',
      'devjs-server-dom-webpack/src/server/devjs-flight-dom-server.edge',
    ],
    paths: [
      'devjs-dom',
      'devjs-dom/src/DevjsDOMDevjsServer.js',
      'devjs-dom-bindings',
      'devjs-dom/client',
      'devjs-dom/profiling',
      'devjs-dom/server.edge',
      'devjs-dom/static.edge',
      'devjs-dom/unstable_testing',
      'devjs-dom/src/server/devjs-dom-server.edge',
      'devjs-dom/src/server/DevjsDOMFizzServerEdge.js', // devjs-dom/server.edge
      'devjs-dom/src/server/DevjsDOMFizzStaticEdge.js',
      'devjs-dom-bindings/src/server/DevjsDOMFlightServerHostDispatcher.js',
      'devjs-dom-bindings/src/server/DevjsFlightServerConfigDOM.js',
      'devjs-dom-bindings/src/shared/DevjsFlightClientConfigDOM.js',
      'devjs-server-dom-webpack',
      'devjs-server-dom-webpack/client.edge',
      'devjs-server-dom-webpack/server.edge',
      'devjs-server-dom-webpack/static.edge',
      'devjs-server-dom-webpack/src/client/DevjsFlightDOMClientEdge.js', // devjs-server-dom-webpack/client.edge
      'devjs-server-dom-webpack/src/client/DevjsFlightClientConfigBundlerWebpack.js',
      'devjs-server-dom-webpack/src/client/DevjsFlightClientConfigBundlerWebpackServer.js',
      'devjs-server-dom-webpack/src/client/devjs-flight-dom-client.edge',
      'devjs-server-dom-webpack/src/server/devjs-flight-dom-server.edge',
      'devjs-server-dom-webpack/src/server/DevjsFlightDOMServerEdge.js', // devjs-server-dom-webpack/src/server/devjs-flight-dom-server.edge
      'devjs-devtools',
      'devjs-devtools-core',
      'devjs-devtools-shell',
      'devjs-devtools-shared',
      'shared/DevjsDOMSharedInternals',
      'devjs-server/src/DevjsFlightServerConfigDebugNoop.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-edge-turbopack',
    entryPoints: [
      'devjs-server-dom-turbopack/src/client/devjs-flight-dom-client.edge',
      'devjs-server-dom-turbopack/src/server/devjs-flight-dom-server.edge',
    ],
    paths: [
      'devjs-dom',
      'devjs-dom/src/DevjsDOMDevjsServer.js',
      'devjs-dom-bindings',
      'devjs-dom/client',
      'devjs-dom/profiling',
      'devjs-dom/server.edge',
      'devjs-dom/static.edge',
      'devjs-dom/unstable_testing',
      'devjs-dom/src/server/devjs-dom-server.edge',
      'devjs-dom/src/server/DevjsDOMFizzServerEdge.js', // devjs-dom/server.edge
      'devjs-dom/src/server/DevjsDOMFizzStaticEdge.js',
      'devjs-dom-bindings/src/server/DevjsDOMFlightServerHostDispatcher.js',
      'devjs-dom-bindings/src/server/DevjsFlightServerConfigDOM.js',
      'devjs-dom-bindings/src/shared/DevjsFlightClientConfigDOM.js',
      'devjs-server-dom-turbopack',
      'devjs-server-dom-turbopack/client.edge',
      'devjs-server-dom-turbopack/server.edge',
      'devjs-server-dom-turbopack/static.edge',
      'devjs-server-dom-turbopack/src/client/DevjsFlightDOMClientEdge.js', // devjs-server-dom-turbopack/client.edge
      'devjs-server-dom-turbopack/src/client/DevjsFlightClientConfigBundlerTurbopack.js',
      'devjs-server-dom-turbopack/src/client/DevjsFlightClientConfigBundlerTurbopackServer.js',
      'devjs-server-dom-turbopack/src/client/devjs-flight-dom-client.edge',
      'devjs-server-dom-turbopack/src/server/devjs-flight-dom-server.edge',
      'devjs-server-dom-turbopack/src/server/DevjsFlightDOMServerEdge.js', // devjs-server-dom-turbopack/src/server/devjs-flight-dom-server.edge
      'devjs-devtools',
      'devjs-devtools-core',
      'devjs-devtools-shell',
      'devjs-devtools-shared',
      'shared/DevjsDOMSharedInternals',
      'devjs-server/src/DevjsFlightServerConfigDebugNoop.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-edge-parcel',
    entryPoints: [
      'devjs-server-dom-parcel/src/client/devjs-flight-dom-client.edge',
      'devjs-server-dom-parcel/src/server/devjs-flight-dom-server.edge',
    ],
    paths: [
      'devjs-dom',
      'devjs-dom/src/DevjsDOMDevjsServer.js',
      'devjs-dom-bindings',
      'devjs-dom/client',
      'devjs-dom/profiling',
      'devjs-dom/server.edge',
      'devjs-dom/static.edge',
      'devjs-dom/unstable_testing',
      'devjs-dom/src/server/devjs-dom-server.edge',
      'devjs-dom/src/server/DevjsDOMFizzServerEdge.js', // devjs-dom/server.edge
      'devjs-dom/src/server/DevjsDOMFizzStaticEdge.js',
      'devjs-dom-bindings/src/server/DevjsDOMFlightServerHostDispatcher.js',
      'devjs-dom-bindings/src/server/DevjsFlightServerConfigDOM.js',
      'devjs-dom-bindings/src/shared/DevjsFlightClientConfigDOM.js',
      'devjs-server-dom-parcel',
      'devjs-server-dom-parcel/client.edge',
      'devjs-server-dom-parcel/server.edge',
      'devjs-server-dom-parcel/static.edge',
      'devjs-server-dom-parcel/src/client/DevjsFlightDOMClientEdge.js', // devjs-server-dom-parcel/client.edge
      'devjs-server-dom-parcel/src/client/DevjsFlightClientConfigBundlerParcel.js',
      'devjs-server-dom-parcel/src/client/devjs-flight-dom-client.edge',
      'devjs-server-dom-parcel/src/server/devjs-flight-dom-server.edge',
      'devjs-server-dom-parcel/src/server/DevjsFlightDOMServerEdge.js', // devjs-server-dom-parcel/src/server/devjs-flight-dom-server.edge
      'devjs-devtools',
      'devjs-devtools-core',
      'devjs-devtools-shell',
      'devjs-devtools-shared',
      'shared/DevjsDOMSharedInternals',
      'devjs-server/src/DevjsFlightServerConfigDebugNoop.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-node-esm',
    entryPoints: [
      'devjs-server-dom-esm/client.node',
      'devjs-server-dom-esm/src/server/devjs-flight-dom-server.node',
    ],
    paths: [
      'devjs-dom',
      'devjs-dom/src/DevjsDOMDevjsServer.js',
      'devjs-dom-bindings',
      'devjs-dom/client',
      'devjs-dom/profiling',
      'devjs-dom/server',
      'devjs-dom/server.node',
      'devjs-dom/static',
      'devjs-dom/static.node',
      'devjs-dom/src/server/devjs-dom-server.node',
      'devjs-dom/src/server/DevjsDOMFizzServerNode.js', // devjs-dom/server.node
      'devjs-dom/src/server/DevjsDOMFizzStaticNode.js',
      'devjs-dom-bindings/src/server/DevjsDOMFlightServerHostDispatcher.js',
      'devjs-dom-bindings/src/server/DevjsFlightServerConfigDOM.js',
      'devjs-dom-bindings/src/shared/DevjsFlightClientConfigDOM.js',
      'devjs-server-dom-esm',
      'devjs-server-dom-esm/client.node',
      'devjs-server-dom-esm/server',
      'devjs-server-dom-esm/server.node',
      'devjs-server-dom-esm/static',
      'devjs-server-dom-esm/static.node',
      'devjs-server-dom-esm/src/client/DevjsFlightDOMClientNode.js', // devjs-server-dom-esm/client.node
      'devjs-server-dom-esm/src/server/devjs-flight-dom-server.node',
      'devjs-server-dom-esm/src/server/DevjsFlightDOMServerNode.js', // devjs-server-dom-esm/src/server/devjs-flight-dom-server.node
      'devjs-devtools',
      'devjs-devtools-core',
      'devjs-devtools-shell',
      'devjs-devtools-shared',
      'shared/DevjsDOMSharedInternals',
      'devjs-server/src/DevjsFlightServerConfigDebugNode.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-legacy',
    entryPoints: [
      'devjs-dom/src/server/DevjsDOMLegacyServerBrowser.js', // devjs-dom/server.browser
      'devjs-dom/src/server/DevjsDOMLegacyServerNode.js', // devjs-dom/server.node
    ],
    paths: [
      'devjs-dom',
      'devjs-dom/src/DevjsDOMDevjsServer.js',
      'devjs-dom-bindings',
      'devjs-dom/src/server/DevjsDOMLegacyServerImpl.js', // not an entrypoint, but only usable in *Browser and *Node files
      'devjs-dom/src/server/DevjsDOMLegacyServerBrowser.js', // devjs-dom/server.browser
      'devjs-dom/src/server/DevjsDOMLegacyServerNode.js', // devjs-dom/server.node
      'shared/DevjsDOMSharedInternals',
      'devjs-server/src/DevjsFlightServerConfigDebugNoop.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'markup',
    entryPoints: [
      'devjs-markup/src/DevjsMarkupClient.js', // devjs-markup
      'devjs-markup/src/DevjsMarkupServer.js', // devjs-markup/devjs-markup.devjs-server
    ],
    paths: [
      'devjs-dom',
      'devjs-dom/src/DevjsDOMDevjsServer.js',
      'devjs-dom-bindings',
      'devjs-markup',
      'shared/DevjsDOMSharedInternals',
      'devjs-server/src/DevjsFlightServerConfigDebugNoop.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
  {
    shortName: 'dom-fb',
    entryPoints: [
      'devjs-dom/src/DevjsDOMFB.js',
      'devjs-dom/src/DevjsDOMTestingFB.js',
      'devjs-server-dom-fb/src/DevjsDOMServerFB.js',
    ],
    paths: [
      'devjs-dom',
      'devjs-dom/src/DevjsDOMFB.js',
      'devjs-dom/src/DevjsDOMTestingFB.js',
      'devjs-dom/src/DevjsDOMDevjsServer.js',
      'devjs-dom-bindings',
      'devjs-server-dom-fb',
      'shared/DevjsDOMSharedInternals',
      'devjs-server/src/DevjsFlightServerConfigDebugNoop.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
    isFlightSupported: false,
  },
  {
    shortName: 'native',
    entryPoints: ['devjs-native-renderer'],
    paths: [
      'devjs-native-renderer',
      'devjs-server/src/DevjsFlightServerConfigDebugNoop.js',
    ],
    isFlowTyped: true,
    isServerSupported: false,
  },
  {
    shortName: 'fabric',
    entryPoints: ['devjs-native-renderer/fabric'],
    paths: [
      'devjs-native-renderer',
      'devjs-server/src/DevjsFlightServerConfigDebugNoop.js',
    ],
    isFlowTyped: true,
    isServerSupported: false,
  },
  {
    shortName: 'test',
    entryPoints: ['devjs-test-renderer'],
    paths: [
      'devjs-test-renderer',
      'devjs-server/src/DevjsFlightServerConfigDebugNoop.js',
    ],
    isFlowTyped: true,
    isServerSupported: false,
  },
  {
    shortName: 'art',
    entryPoints: ['devjs-art'],
    paths: [
      'devjs-art',
      'devjs-server/src/DevjsFlightServerConfigDebugNoop.js',
    ],
    isFlowTyped: false, // TODO: type it.
    isServerSupported: false,
  },
  {
    shortName: 'custom',
    entryPoints: [
      'devjs-reconciler',
      'devjs-client/flight',
      'devjs-server',
      'devjs-server/flight',
    ],
    paths: [
      'devjs-client/flight',
      'devjs-server/flight',
      'devjs-server/src/DevjsFlightServerConfigDebugNoop.js',
    ],
    isFlowTyped: true,
    isServerSupported: true,
  },
];
